---
image: rsprta/molecule-runner
services:
  - docker:dind

stages:
  - lint
  - release

before_script:
  - docker -v
  - python3 -V
  - ansible --version
  - molecule --version

lint:yamllint:
  stage: lint
  script:
    - yamllint .

lint:ansible-lint:
  stage: lint
  script:
    - ansible-lint --exclude molecule/default/vars.yml

release:galaxy:
  stage: release
  script:
    - ansible-galaxy role import --token $GALAXY_TOKEN $GITLAB_USER_LOGIN $CI_PROJECT_NAME
  only:
    - tags
