---
image: quay.io/ansible/toolset
services:
  - docker:dind

stages:
  - release

before_script:
  - docker -v
  - python3 -V
  - ansible --version
  - molecule --version

release:galaxy:
  stage: release
  script:
    - ansible-galaxy role import --token $GALAXY_TOKEN $GITLAB_USER_LOGIN $CI_PROJECT_NAME
  only:
    - tags
