---
- name: Create ZFS datasets
  zfs:
    name: "{{ item.name }}"
    state: present
    extra_zfs_properties: "{{ item | remove_key('name') }}"
  with_items: "{{ zfs_datasets }}"
  loop_control:
    label: "{{ item.name }}"
