---
- name: Include system-specific vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Set ZFS package variable
  ansible.builtin.set_fact:
    zfs_packages: "{{ __zfs_packages }}"
  when: zfs_packages is undefined

- name: Install OS packages
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Configure pool
  ansible.builtin.include_tasks: "pool.yml"
  when: zfs_pools | length > 0

- name: Configure datasets
  ansible.builtin.import_tasks: "datasets.yml"
