---
- name: Check if pool exists
  ansible.builtin.shell: set -o pipefail; zpool list -H | cut -s -f1
  args:
    executable: /bin/bash
  changed_when: false
  register: existing_pools

- name: Create zpool
  ansible.builtin.shell: >-
    set -o pipefail;
    echo "{{ item.passphrase | default('') }}" |
    zpool create -f -o ashift={{ item.ashift | default(12) }}
    -O acltype={{ item.acltype | default('posixacl') }}
    -O canmount=off
    -O compression={{ item.compression | default('lz4') }}
    -O dnodesize={{ item.dnodesize | default('auto') }}
    -O normalization={{ item.normalization | default('formD') }}
    -O relatime={{ item.relatime | default('on') }}
    -O xattr={{ item.xattr | default('sa') }}
    {% if item.passphrase is defined %}
    -O encryption={{ item.encryption | default('aes-256-gcm') }}
    -O keylocation={{ item.keylocation | default('prompt') }}
    -O keyformat={{ item.keyformat | default('passphrase') }}
    {% endif %}
    {{ item.name }}
    {{ item.type | default('') }}
    {% for device in item.devices %} {{ device }} {% endfor %}
  args:
    executable: /bin/bash
  when: item.name not in existing_pools.stdout
  with_items: "{{ zfs_pools }}"
  loop_control:
    label: "{{ item.name }}"
