---
- name: Prepare
  hosts: all

  vars_files:
    - vars.yml

  tasks:
    - name: "Install ZFS"
      ansible.builtin.apt:
        name: "zfsutils-linux"
        state: present
        update_cache: true

    - name: "Create disk files"
      ansible.builtin.command: dd if=/dev/zero of={{ item }} bs=1M count=256
      args:
        creates: "{{ item }}"
      with_items: "{{ zfs_pools[0].devices }}"
